apiVersion: apps/v1
kind: Deployment
metadata:
  name: java
  namespace: default
  labels:
    app: java
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 0
  selector:
    matchLabels:
      app: java
  template:
    metadata:
      labels:
        app: java
    spec:
      containers:
        - name: java
          image: saranyamagi/simplejavaproject:1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
